In [1]:
from numpy import random

In [2]:
x = random.normal(size=(2, 3))
# print(x)

[[-0.80142772 -0.37847224 -1.85240188]
 [-1.19291315  1.28868519  0.38434664]]


In [3]:
X = random.normal(loc=1, scale=2, size=(2, 3))
print(x)

[[-0.80142772 -0.37847224 -1.85240188]
 [-1.19291315  1.28868519  0.38434664]]
